import fs from "fs";
import { randomUUID } from "crypto";
import { getJob, updateJob } from "../store/jobStore";
import { jobDir, clipVideoPath, clipThumbPath, clipSrtPath, autoGeneratedSrtPath } from "../paths";
import { downloadVideo, downloadYoutubeSubtitles, getVideoInfo } from "./youtube";
import { cutClip, generateThumbnail } from "./ffmpeg";
import { transcribeToSrt } from "./transcribe";
import { computeClipPlan } from "./clipMath";
import { parseSrt, shiftAndWindow, stringifySrt } from "./srt";
import { Clip } from "../types";

/**
 * Marks a job `failed` with a short, non-technical message for end users
 * (per API_CONTRACT.md's error shape: "keep messages non-technical"), while
 * logging the full technical error (yt-dlp/ffmpeg stderr, proxy errors,
 * stack traces, etc.) server-side so it's still debuggable.
 */
function failJob(jobId: string, phase: string, err: unknown, userMessage: string): void {
  console.error(`Job ${jobId} failed during ${phase}:`, err);
  updateJob(jobId, {
    status: "failed",
    progress: 100,
    error: userMessage,
    message: "Failed.",
  });
}

/**
 * Walks a job through fetching_info -> downloading -> processing ->
 * completed|failed. Never throws — every failure path marks the job
 * `failed` with a message instead of propagating, so a bad job can never
 * crash the process or leave an unhandled rejection behind.
 */
export async function processJob(jobId: string): Promise<void> {
  const job = getJob(jobId);
  if (!job) return;

  updateJob(jobId, {
    status: "fetching_info",
    progress: 5,
    message: "Fetching video info…",
  });

  let info;
  try {
    info = await getVideoInfo(job.sourceUrl);
  } catch (err) {
    failJob(
      jobId,
      "fetching video info",
      err,
      "Couldn't fetch this video — it may be private, region-locked, or the link is invalid."
    );
    return;
  }

  updateJob(jobId, {
    videoTitle: info.title,
    videoDurationSeconds: info.duration,
    videoThumbnail: info.thumbnail,
  });

  updateJob(jobId, {
    status: "downloading",
    progress: 15,
    message: "Downloading video…",
  });

  let sourcePath: string;
  try {
    await fs.promises.mkdir(jobDir(jobId), { recursive: true });
    sourcePath = await downloadVideo(job.sourceUrl, jobDir(jobId));
  } catch (err) {
    failJob(
      jobId,
      "downloading video",
      err,
      "Couldn't download this video — it may be private, region-locked, or the link is invalid."
    );
    return;
  }

  const lang = job.options.subtitleLang || "en";
  let sourceSrtPath: string | undefined;

  try {
    if (job.options.subtitles === "youtube") {
      updateJob(jobId, { message: "Fetching YouTube captions…" });
      sourceSrtPath = await downloadYoutubeSubtitles(job.sourceUrl, jobDir(jobId), lang);
      if (!sourceSrtPath) {
        updateJob(jobId, {
          message: "No YouTube captions available for this video/language — continuing without subtitles.",
        });
      }
    } else if (job.options.subtitles === "auto-generate") {
      updateJob(jobId, {
        status: "processing",
        progress: 30,
        message: "Transcribing audio (this can take a while)…",
      });
      // Any failure here (most commonly: faster-whisper not installed)
      // throws with an actionable message and fails the whole job, per
      // spec — auto-generate is a real feature with a real optional
      // dependency, not a stub that silently pretends to work.
      const srtOut = autoGeneratedSrtPath(jobId, lang);
      await transcribeToSrt(sourcePath, srtOut, lang);
      sourceSrtPath = srtOut;
    }
  } catch (err) {
    failJob(
      jobId,
      "generating subtitles",
      err,
      "Couldn't generate subtitles for this video. Try again, or choose a different subtitle option."
    );
    return;
  }

  try {
    updateJob(jobId, {
      status: "processing",
      progress: 40,
      message: "Computing clip plan…",
    });

    const plan = computeClipPlan(job.options.numClips, job.options.clipLength, info.duration);

    let sourceCues = sourceSrtPath && fs.existsSync(sourceSrtPath)
      ? parseSrt(await fs.promises.readFile(sourceSrtPath, "utf8"))
      : undefined;

    const clips: Clip[] = [];

    for (let i = 0; i < plan.starts.length; i++) {
      const clipId = randomUUID();
      const start = plan.starts[i];
      const duration = plan.length;

      updateJob(jobId, {
        progress: 40 + Math.round((i / plan.starts.length) * 55),
        message: `Cutting clip ${i + 1} of ${plan.starts.length}…`,
      });

      let srtForClip: string | undefined;
      let hasSubtitles = false;

      if (sourceCues && sourceCues.length > 0) {
        const windowed = shiftAndWindow(sourceCues, start, start + duration);
        if (windowed.length > 0) {
          srtForClip = clipSrtPath(jobId, clipId);
          await fs.promises.writeFile(srtForClip, stringifySrt(windowed), "utf8");
          hasSubtitles = true;
        }
      }

      const outPath = clipVideoPath(jobId, clipId);
      await cutClip({ source: sourcePath, start, duration, output: outPath, srtPath: srtForClip });
      await generateThumbnail({
        source: outPath,
        output: clipThumbPath(jobId, clipId),
        atSeconds: Math.min(1, duration / 2),
      });

      clips.push({
        id: clipId,
        index: i,
        startTime: start,
        duration,
        hasSubtitles,
        downloadUrl: `/api/jobs/${jobId}/clips/${clipId}/download`,
        thumbnailUrl: `/api/jobs/${jobId}/clips/${clipId}/thumbnail`,
      });

      updateJob(jobId, { clips: [...clips] });
    }

    updateJob(jobId, {
      status: "completed",
      progress: 100,
      message: plan.message ?? `Created ${clips.length} clip${clips.length === 1 ? "" : "s"}.`,
      clips,
    });
  } catch (err) {
    failJob(
      jobId,
      "creating clips",
      err,
      "Something went wrong while creating your clips. Please try again."
    );
  }
}
