import path from "path";

// All job/clip files live under storage/<jobId>/... by convention, so the
// download/thumbnail routes never need to look anything up beyond the ids in
// the URL — no internal-only fields need to leak into the public Job/Clip
// JSON shapes.

export const STORAGE_ROOT = path.join(__dirname, "..", "storage");

export function jobDir(jobId: string): string {
  return path.join(STORAGE_ROOT, jobId);
}

export function clipVideoPath(jobId: string, clipId: string): string {
  return path.join(jobDir(jobId), `clip_${clipId}.mp4`);
}

export function clipThumbPath(jobId: string, clipId: string): string {
  return path.join(jobDir(jobId), `clip_${clipId}_thumb.jpg`);
}

export function clipSrtPath(jobId: string, clipId: string): string {
  return path.join(jobDir(jobId), `clip_${clipId}.srt`);
}

/** Where an auto-generated (whisper) SRT for the full source video lives. */
export function autoGeneratedSrtPath(jobId: string, lang: string): string {
  return path.join(jobDir(jobId), `source.${lang}.srt`);
}
